SELECT p.*
FROM PAYMENT p
         JOIN PUBLIC.PAYMENTTYPE P2 ON P2.ID = p.TYPE_ID
WHERE P2.NAME = 'MONTHLY';

SELECT m.*
FROM MARK m
         JOIN SUBJECT S ON S.ID = m.SUBJECT_ID
WHERE S.NAME = 'Art';

SELECT s.*
FROM STUDENT s
         JOIN PAYMENT p ON s.ID = p.STUDENT_ID
         JOIN PAYMENTTYPE pt ON p.TYPE_ID = pt.ID
WHERE pt.NAME = 'WEAKLY';

SELECT s.*
FROM STUDENT s
         JOIN MARK M ON s.ID = M.STUDENT_ID
         JOIN SUBJECT su ON M.SUBJECT_ID = su.ID
WHERE su.NAME = 'Math';